name: Copy Docs to gh-pages

on:
  push:
    branches:
      - main

jobs:
  copy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "youremail@example.com"

      - name: Copy docs to gh-pages branch
        run: |
          git checkout gh-pages
          git checkout main -- docs
          git add -A
          git commit -m "Update docs from main"
          git push origin gh-pages